<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FixItNepal.Domain\FixItNepal.Domain.csproj" />
    <ProjectReference Include="..\FixItNepal.Domain.Shared\FixItNepal.Domain.Shared.csproj" />
    <ProjectReference Include="..\FixItNepal.Application.Contracts\FixItNepal.Application.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
